### ISSUE TITLE
Short Question :-)

### ISSUE THREAD

**Issue by dennismaxjung** [a-gal/one-node-wonder#127]
I saw that you also use immich with an nvidia GPU for machine learning? Does it work for you? Are there no errors in the logs of the ImmichML pod? I have a similarly set up cluster, but I always get a SIGSEGV. Maybe you have some hints how you get it working.

**Comment by dennismaxjung** [comment]
I’ve already checked all of that, and a test container with nvidia-smi works and provides output. However, neither ffmpeg in the microservice container nor ML in the machine learning container are working for me. (operation not permitted ffmpeg and SIGSEGV on ml) So, I assume the issue isn’t in the cluster. Thanks to you, I can rule out one potential source of the problem and focus on whether GPU passthrough in Proxmox is causing the issue. I’m also ruling out the GPU itself since it worked for me under TrueNAS Scale.

**Comment by a-gal** [comment]
It still might be something to do with nvidia-device-plugin (runtime class/pod-security on namespace?), since working nvidia-smi kinda hints at successful passthrough. GL with your research!

**Comment by dennismaxjung** [comment]
> It still might be something to do with nvidia-device-plugin (runtime class/pod-security on namespace?)

Yeah, this was the hint i needed, i checked all pods of immich again and found out it seams the runtimeclass is not set on the pods. Besides i also set the defaultruntimeclass within talconfig as you do. So i checked this. It seems it was not configured on the node. After some trying it catched up the config and it worked

Thank You 👍
